version: '3'

volumes:
  seolynn_language_main_app_local_postgres_data: {}
  seolynn_language_main_app_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: seolynn_language_main_app_local_django
    container_name: seolynn_language_main_app_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: seolynn_language_main_app_production_postgres
    container_name: seolynn_language_main_app_local_postgres
    volumes:
      - seolynn_language_main_app_local_postgres_data:/var/lib/postgresql/data
      - seolynn_language_main_app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: seolynn_language_main_app_local_docs
    container_name: seolynn_language_main_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./seolynn_language_main_app:/app/seolynn_language_main_app:z
    ports:
      - "9000:9000"
    command: /start-docs

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: seolynn_language_main_app_frontend
    depends_on:
      - django
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - 81:80
